### ISSUE TITLE
Unify generic "convert binary op" patterns

### ISSUE THREAD

**Issue by j2kun** [google/heir#1150]
I see this pattern in like 5 places in our codebase. I think we can refactor it to a single location and reuse it.

```cpp
template <typename SourceOp, typename TargetOp>
struct ConvertBinaryOp : public OpConversionPattern<SourceOp> {
  ConvertBinaryOp(mlir::MLIRContext *context)
      : OpConversionPattern<SourceOp>(context) {}

  using OpConversionPattern<SourceOp>::OpConversionPattern;

  LogicalResult matchAndRewrite(
      SourceOp op, typename SourceOp::Adaptor adaptor,
      ConversionPatternRewriter &rewriter) const override {
    rewriter.replaceOpWithNewOp<TargetOp>(op, adaptor.getLhs(),
                                              adaptor.getRhs());
    return success();
  }
};
```

**Comment by AlexanderViand-Intel** [comment]
I looked at this while working on #1196 and this seems harder than expected, because each version of the conversion has some context-specific parts. For example, the OpenFHE-related version of this adds the `cryptoContext` argument to the argument list and similar for the TFHE-rust related version. That leaves the uses in `ArithToModArith` (this is actually a "pure" instance) and `PolynomialToModArith` but the latter does some type-based switching that the "pure" version doesn't have.
