### ISSUE TITLE
Factor a secret.generic down to loop bodies

### ISSUE THREAD

**Issue by j2kun** [google/heir#306]
As a step toward tf2fhe, we start with a pass that encloses an entire function's body in secret.generic, and a later step converts a secret.generic to an optimized boolean circuit. We want that second step to apply only to the bodies of `affine.for` loop nests, as well as to the sections of ops that occur between loop nests.

This issue is to write a pattern similar to `distribute-generic`, but which stops short of converting everything to single-op generics, according to some configuration that specifies what the boundary is.

Because `affine.for` is intimately related to `affine.load` and `affine.store`, we should also hoist those ops outside of a secret.generic.

**Comment by j2kun** [comment]
Remaining TODO: split a secret.generic when the op that can be factored through is mid-way through the generic's body.

**Comment by asraa** [comment]
> I think we'd need to do this anyway for our immediate plan, because we can't include the loads/stores in the yosys optimizer. 

Why not? In your current example, I agree, since we can't translate the generic as a self-contained module unless the allocated memref is an argument to secret. In general though, we can translate loads and stores to read and writes to arrays in yosys. 

I think... actually... how do we get around the removal of IsolatedFromAbove in general with yosys optimizer?

To me, the original testcase should have hoisted an allocated memref to the following, but I know this breaks the usual type conversion to secret types as `secret<memref<10x...>>`, which means you can't read/write/allocate as normal memrefs anymore.
```
%alloc = memref.alloc() : memref<10xsecret<i8>>
```

**Comment by j2kun** [comment]
Just added https://github.com/google/heir/pull/324, which should handle the issue about isolation: greedily apply that pattern at the start of the yosys optimizer pass, and it will capture all the ambient scope as (non-secret) arguments to the generic.
