### ISSUE TITLE
poly: use poly.ntt as a rewrite for polynomial.mul 

### ISSUE THREAD

**Issue by asraa** [google/heir#680]
Right now `--bgv-to-polynomial` uses `polynomial.mul`, and we should create a rewrite pattern that converts `polynomial.mul` to a `polynomial.ntt` and tensor elementwise multiplication (with moduli?) 

OR should this just be the default lowering from `bgv.mul` to `polynomial.ntt`, multiplication, and `polynomial.intt`?

**Comment by AlexanderViand-Intel** [comment]
I think it'd be nice to have this be a separate pass, both because it's conceptually neater and because it'd allow pipelines for targets that don't have efficient NTT implementations to substitute their own "fast poly.mul" lowering pass. In practice, though, it's not entirely clear to me at the moment how parameter selection/etc would work with a design where such decision are left until such a late point in the compilation.

**Comment by asraa** [comment]
Oh thank you! I wanted to experiment with it and I'll clone the PR. Thanks!
